version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend-service
    ports:
      - "8404:8404"

  frontend:
    build: ./frontend
    container_name: frontend-service
    ports:
      - "3000:3000"
    depends_on:
      - backend