import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/NavBar";
// import { headers } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Social network",
  description: "Generated by create next app",
};


export default async function RootLayout({ children }) {

  // const pathname = await headers().get('x-nextjs-route');
  // console.log(pathname);

  // let isLoggedIn = false;

  // try {
  //   const response = await fetch("http://localhost:8404/", {
  //     method: "GET",
  //     headers: {
  //       "Content-Type": "application/json",
  //     },
  //     credentials: "include",
  //   });

  //   if (response.ok) {
  //     isLoggedIn = await response.json();
  //   }
  // } catch (error) {
  //   setError(true);
  //   console.error("Error checking login status:", error);
  // }

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
